# This is a url that Jekyll will use to generate all links to your site. Your site should be published to this domain.
# Make sure that you either own the domain, or that it is the github.io subdomain from your user or organisation.
url: https://slideclimb.github.io
# The url path that Jekyll appends to your url before generating all the other paths when generating links. When using
# Jekyll to generate a site hosted on GitHub via a repo that is not <username>.github.io, this should be the name of the
# repo, because GitHub Pages publishes to https://<username>.github.io/<repository>.
baseurl: /jekyll-polyglot-template

author: slideclimb


# polyglot settings
languages: ["en", "nl"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", "assets/css", "assets/img"]
parallel_localization: true

sass:
  sourcemap: never


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot